function(quoted_initializer_list VAR_NAME)
    set(${VAR_NAME} "{")
    set(comma FALSE)
    foreach(arg ${ARGN})
        if (comma)
            set(${VAR_NAME} "${${VAR_NAME}}, ")
        endif()
        set(${VAR_NAME} "${${VAR_NAME}}\"${arg}\"")
        set(comma TRUE)
    endforeach()
    set(${VAR_NAME} "${${VAR_NAME}}}" PARENT_SCOPE)
endfunction()