#!/usr/bin/perl -w

use strict;
print <<EOD;
/* This is an AUTOGENERATED file from IANA registered headers descpriptions.
 */

#include <tip/http/common/grammar/header_parse.hpp>

namespace tip {
namespace http {
namespace grammar {
namespace parse {

known_header_name_grammar::known_header_name_grammar()
{
	add
EOD

while (<>) {
	s/\r\n//g;
	my ($header, $template, $protocol, $status, $reference) = split(',', $_, 5);
	$reference =~ s/"//g;
	$reference =~ s/\n//;
	my $enum_val = $header;
	$enum_val =~ s/-//g;
	my $header_lc = lc($header);
	
	print "\t\t(\"$header\", $enum_val)\n";
	print "\t\t(\"$header_lc\", $enum_val)\n";
}

print <<EOD;
	;
}

}  // namespace parse
}  // namespace grammar
}  // namespace http
}  // namespace tip
EOD

