#!/usr/bin/perl -w

use strict;

print <<EOD;
/* This is an AUTOGENERATED file from IANA registered headers descpriptions.
 */

#ifndef TIP_HTTP_COMMON_HEADER_NAMES_HPP_
#define TIP_HTTP_COMMON_HEADER_NAMES_HPP_

namespace tip {
namespace http {

enum known_header_name {
EOD

while (<>) {
	s/\r\n//g;
	my ($header, $template, $protocol, $status, $reference) = split(',', $_, 5);
	$reference =~ s/"//g;
	$reference =~ s/\n//;
	my $enum_val = $header;
	$enum_val =~ s/-//g;
	$status ||= "provisional";

	print "\t$enum_val, /**< $header: $reference ($status) $template */\n";
}

print <<EOD;

};

}  // namespace http
}  // namespace tip

#endif /* TIP_HTTP_COMMON_HEADER_NAMES_HPP_ */
EOD

